### PR TITLE
Change tester config to run head instead of tail for RISC-V

### PR DESCRIPTION
**Pull request by quinnlp**
When running rars, we want to trim the last 2 lines of the output (they are garbage).

### CODE REVIEW

**Review by rcunrau — APPROVED** [review]
Hmm, I seem to be running OK with tail and +3

**Comment by quinnlp** [comment]
Interesting, if you're exiting the program with `ecall` `10`, I think the last 2 lines will always be:
```
<\n>
Program terminated by calling exit
```

**Comment by rcunrau** [comment]
On Mac I get: 

```
runrau@Rons-MacBook-Pro tests % ./rars.sh state_cond-risc.s
RARS 1.6  Copyright 2003-2019 Pete Sanderson and Kenneth Vollmar

0
runrau@Rons-MacBook-Pro tests %
```

**Comment by quinnlp** [comment]
I see, I found out why this is happening.

```shell
qpham@ohaton:~>cat test.s
.data

nl:
.asciz "\n"

.text

li a0, 43
li a7, 1
ecall

la a0, nl
li a7, 4
ecall

li a7, 10
ecall
qpham@ohaton:~>rars test.s
43

Program terminated by calling exit
qpham@ohaton:~>which rars
/usr/local/bin/rars
qpham@ohaton:~>cat /usr/local/bin/rars
#!/bin/bash
RARSPath=/usr/local/share/rars-20230109/rars_20230109.jar
if [ $# -eq 0 ]
  then
    java -jar $RARSPath
  else
    java -jar $RARSPath nc me "$@"
fi
qpham@ohaton:~>java -jar /usr/local/share/rars-20230109/rars_20230109.jar "test.s"
RARS 1.5  Copyright 2003-2019 Pete Sanderson and Kenneth Vollmar

43
qpham@ohaton:~>
```

On the lab machine `rars` is a wrapper that adds some options and alters the output. Since the `rars` wrapper is used by cmput229 I think we should keep it this way and notify the students that they should be testing the SCalc backends on the lab machines (they can still test the interpreter on their own machines).

**Comment by rcunrau** [comment]
I would think by this point they can change their local SCalcConfigCS.json to just make it work. But yes, having the default set to work on the CS lab machines is the right way to go.

**Pull request merged**
